import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "styled-components";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Matchmaker",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
